# Reshaping ops — squeeze, unsqueeze, view vs reshape, permute, transpose.

In [1]:
import torch

# create matrix
torch.manual_seed(42)
mat1 = torch.randint(1,9,size=(2,4))
print(f"mat1 shape:{mat1.shape}")
print(f"mat1 number:{mat1.numel()}")
print(f"mat1 :{mat1}")


mat1 shape:torch.Size([2, 4])
mat1 number:8
mat1 :tensor([[7, 4, 5, 7],
        [3, 8, 5, 5]])


In [2]:
#squeeze
# print(torch.squeeze(mat1))
#reshape
print("reshape(8,1):",mat1.reshape(8,1))
mat1_reshaped = mat1.reshape(8,1)
#squeeze
print("squeeze:",torch.squeeze(mat1_reshaped))
mat1_squeeze = torch.squeeze(mat1_reshaped)
print("Unsqueeze-dim0",torch.unsqueeze(mat1_squeeze,dim=0))
print("Unsqueeze-dim1",torch.unsqueeze(mat1_squeeze,dim=1))



reshape(8,1): tensor([[7],
        [4],
        [5],
        [7],
        [3],
        [8],
        [5],
        [5]])
squeeze: tensor([7, 4, 5, 7, 3, 8, 5, 5])
Unsqueeze-dim0 tensor([[7, 4, 5, 7, 3, 8, 5, 5]])
Unsqueeze-dim1 tensor([[7],
        [4],
        [5],
        [7],
        [3],
        [8],
        [5],
        [5]])


In [3]:
mat1_reshaped = mat1.reshape(1,8) 
print(f"mat1.reshape(1,8){mat1_reshaped}") #[[....]]
#squeeze 
mat1_squeeze = mat1_reshaped.squeeze()
print(torch.squeeze(mat1_reshaped)) #[...]
print("Unsqueeze-dim0",torch.unsqueeze(mat1_squeeze,dim=0))#[[...]]
print("Unsqueeze-dim1",torch.unsqueeze(mat1_squeeze,dim=1))#[[] [][]...]

mat1.reshape(1,8)tensor([[7, 4, 5, 7, 3, 8, 5, 5]])
tensor([7, 4, 5, 7, 3, 8, 5, 5])
Unsqueeze-dim0 tensor([[7, 4, 5, 7, 3, 8, 5, 5]])
Unsqueeze-dim1 tensor([[7],
        [4],
        [5],
        [7],
        [3],
        [8],
        [5],
        [5]])


# 3D squeeze


In [4]:
matrix_3d = torch.arange(1,17).reshape(1,4,4)
matrix_3d

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]])

In [5]:
m_squeeze = matrix_3d.squeeze()
print("Squeeze:",m_squeeze)

Squeeze: tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])


In [6]:
m_unsqueeze = torch.unsqueeze(m_squeeze,dim=0)#[[[]]]
print(m_unsqueeze)
m_unsqueeze = torch.unsqueeze(m_squeeze,dim=1)#[[[][][]]]
print(m_unsqueeze)
m_unsqueeze = torch.unsqueeze(m_squeeze,dim=2)#[[[1][2][3]]]
print(m_unsqueeze)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]])
tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]],

        [[13, 14, 15, 16]]])
tensor([[[ 1],
         [ 2],
         [ 3],
         [ 4]],

        [[ 5],
         [ 6],
         [ 7],
         [ 8]],

        [[ 9],
         [10],
         [11],
         [12]],

        [[13],
         [14],
         [15],
         [16]]])


In [7]:
matrix_3d = torch.arange(1,5).reshape(1,4,1)
print(matrix_3d)

tensor([[[1],
         [2],
         [3],
         [4]]])


In [8]:
m_squeeze = matrix_3d.squeeze()
print(m_squeeze)
m_squeeze = matrix_3d.squeeze(dim=0)
print(m_squeeze)
m_squeeze = matrix_3d.squeeze(dim=2)
print(m_squeeze)

tensor([1, 2, 3, 4])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1, 2, 3, 4]])


In [9]:
#unsqueeze
m_squeeze = matrix_3d.squeeze()
print(m_squeeze)

m_unsqueeze_dim0 = torch.unsqueeze(m_squeeze,dim=0)
print(m_unsqueeze_dim0)

m_unsqueeze_dim2 = torch.unsqueeze(m_unsqueeze_dim0,dim=2)
print(m_unsqueeze_dim2,m_unsqueeze_dim2.shape)

# m_unsqueeze_dim2 = torch.unsqueeze(m_unsqueeze_dim1,dim=2)
# print(m_unsqueeze_dim2,m_unsqueeze_dim2.shape)

tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])
tensor([[[1],
         [2],
         [3],
         [4]]]) torch.Size([1, 4, 1])


In [10]:
torch.arange(1,13).reshape(3,2,2)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

# reshape vs view

Feature             view()                                             reshape()
Data Sharing   Always returns a view (shares the same data).     Returns a view when possible; otherwise returns a copy.Contiguity    Requires the tensor to be contiguous in memory.      Can handle both contiguous and non-contiguous tensors.
Error Handling  Throws a RuntimeError if the tensor is non-contiguous.   Automatically copies data if needed to fulfill the new shape.

Note:
The outputs look identical — the real difference is about memory, not the result.The outputs are identical — the difference is invisible in print but very real under the hood.

Practical rule for nn: just use reshape everywhere. Use view only when you intentionally want to share memory and catch non-contiguous bugs early. In 99% of model code you'll see reshape.

In [11]:
mat1 = torch.arange(1,10).reshape(3,3)
print(mat1)

mat1 = mat1 + 3
print(mat1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [12]:
mat1 = torch.arange(1,10).view((3,3))
print(mat1)

mat1 = mat1 + 3
print(mat1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [13]:
# proof of non - contiguous
t = torch.arange(1,5).reshape(2,2)
v = t.view((4))

t[0,0]= 9   # upating t is updating v
print(t)
print(v)

#transpose creates non-contighuous
t1 = t.T
print(t1)
print(t1.reshape(4))
print(t1)
print(t1.contiguous().view(4)) # if we dont use contiguous, throws error - view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

tensor([[9, 2],
        [3, 4]])
tensor([9, 2, 3, 4])
tensor([[9, 3],
        [2, 4]])
tensor([9, 3, 2, 4])
tensor([[9, 3],
        [2, 4]])
tensor([9, 3, 2, 4])


# permute, transpose

Difference between T and transpose:
shape [2, 3, 4] => t3.T     =>  reverses ALL dims → shape [4, 3, 2]
torch.transpose(t3, 0, 1)     # swaps ONLY dim0 and dim1 → shape [3, 2, 4]
torch.transpose(t3, 1, 2)     # swaps ONLY dim1 and dim2 → shape [2, 4, 3]

.T / .transpose()
    → no copy
    → same memory
    → strides flipped
    → is_contiguous() = False
    → view() will ERROR
    → reshape() works (makes a copy internally when needed)

.contiguous()
    → forces a real copy
    → reorders memory to match strides
    → is_contiguous() = True
    → view() works again

t.T.is_contiguous()              # False  — no copy yet
t.T.contiguous().is_contiguous() # True   — NOW a copy was made
t.T.reshape(6)                   # copy made silently inside reshape
t.T.view(6)                      # ERROR  — refuses to copy

Note : Only .clone(), .contiguous(), or reshape (when forced) actually allocate new memory.


In [14]:
mat1 = torch.arange(1,25).reshape(2,3,4)
print(mat1, mat1.shape)

# T
# print(mat1.T)

#transpose
print(torch.transpose(mat1,0,1))#shape (3,2,4)


tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]) torch.Size([2, 3, 4])
tensor([[[ 1,  2,  3,  4],
         [13, 14, 15, 16]],

        [[ 5,  6,  7,  8],
         [17, 18, 19, 20]],

        [[ 9, 10, 11, 12],
         [21, 22, 23, 24]]])


# permute

Tensor.permute(*dims)

Feature                         torch.transpose                             torch.permute
SwappingScope : Can only swap two dimensions at a time.          Can rearrange any number of dimensions simultaneously.Input Requirement : Takes the indices of the two dimensions to be swapped.  Requires the full desired order of all dimensions.
Common Use :  Swapping batch and sequence length or simple matrix transposition.  Converting image formats (e.g., (C, H, W) to (H, W, C)).

In [15]:
mat1 = torch.arange(1,25).reshape(3,2,4)
print(mat1.size())

mat2 = mat1.permute(1,2,0) #(2,4,3)
print(mat2.shape)
print(mat2)

# use 

torch.Size([3, 2, 4])
torch.Size([2, 4, 3])
tensor([[[ 1,  9, 17],
         [ 2, 10, 18],
         [ 3, 11, 19],
         [ 4, 12, 20]],

        [[ 5, 13, 21],
         [ 6, 14, 22],
         [ 7, 15, 23],
         [ 8, 16, 24]]])


# Broadcasting rules -> Important

Rule 1 — align shapes from the RIGHT, pad 1s on the left
Rule 2 — a size-1 dim expands to match the other tensor's size
Rule 3 — if neither dim is 1 and they differ → ERROR

In [18]:
#RULE 1  align shapes from the RIGHT, pad 1s on the left

t1 = torch.ones(3,1) # shape (3,1)
t2 = torch.ones(4)   # shape(1,4) -> rule applied here

print(f"t1 shape:{t1.shape},t2 shape : {t2.shape}")
t3 = t1 + t2
print(t1,t2)
print(t3,t3.shape) # shape of t3 = (3,4)

#Rule 2 — a size-1 dim expands to match the other tensor's size
t1 = torch.ones(3,1)
t2 = torch.ones(1,4)
t3 = t1+t2
print(t3,t3.shape) # shape of t3 = [3, 4]  ← 3×1 expands to 3×4

#Rule 3 — if neither dim is 1 and they differ → ERROR
t1 = torch.ones(3,2)
t2 = torch.ones(1,4)
t3 = t1+t2 # RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 1
print(t3,t3.shape) # shape of t3 = [3, 4]  ← 3×1 expands to 3×4


t1 shape:torch.Size([3, 1]),t2 shape : torch.Size([4])
tensor([[1.],
        [1.],
        [1.]]) tensor([1., 1., 1., 1.])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]) torch.Size([3, 4])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]) torch.Size([3, 4])


RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 1

Expaliantion:
Step 1 — Rule 1 kicks in first (pad 1s on the left):
[32, 10]
[    10]  ← shorter, so pad left with 1 → [1, 10]
Step 2 — Rule 2 kicks in (size-1 expands):
[32, 10]
[ 1, 10]  ← dim0 is 1, expands to 32
─────────
[32, 10]  ← result
Now your confusion — why does [3,2] + [1,4] fail but [32,10] + [10] work?
[3, 2]        [32, 10]
[1, 4]        [ 1, 10]  ← after padding

dim0: 3 vs 1  ✅ (one is 1, expands)    dim0: 32 vs 1  ✅ (one is 1, expands)
dim1: 2 vs 4  ❌ (neither is 1, ERROR)  dim1: 10 vs 10 ✅ (equal, no expand needed)
The key difference is dim1:

2 vs 4 → neither is 1, not equal → ERROR
10 vs 10 → equal → fine

So the rule to check for any dim pair is simply:
dim_a == dim_b        ✅ equal — no expand needed
dim_a == 1            ✅ a expands to match b
dim_b == 1            ✅ b expands to match a
none of the above     ❌ ERROR

In [ ]:
#exercise 

output = torch.ones(10,3)  #shape (10,3)
bias = torch.ones(1,3) # shape(1,3)
result = output + bias

output , result


(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]))