# Gradient basics — requires_grad=True, tensor.grad, tensor.backward(), torch.no_grad(). This is the bridge to nn.

In [ ]:
import torch

x = torch.tensor([3.0,1.0],requires_grad=True) # # tell PyTorch to track this
y = x ** 2   # forward pass — build the computation
loss = y.sum() # compute loss whcih gives scalar value

loss.backward() # backward() expects a scalar, which loss functions always give you.  # backward pass — compute gradients
print(x.grad) # tensor(6.,2.0) ← dy/dx = 2*3 = 6 ✅,dy/dx = 2*1 = 2


# Why no_grad matters

During training:   need gradients → track everything
During validation: just need predictions → no_grad saves memory + speed
During inference:  same — wrap in no_grad always

In [ ]:
x = torch.tensor(3.0,requires_grad=True)
y = torch.tensor(3.0)

loss = x ** 2 + 2 * x +1
loss.backward()
print(x.grad)

x.grad.zero_()

# During inference/validation — don't waste memory tracking gradients
with torch.no_grad():
    pred = x ** 2
    print(pred)




# Stacking & concatenation — torch.stack vs torch.cat.

stack → all tensors must be IDENTICAL shape. Whenever we stack, it increase the dimension. If vector stack - 1D to 2D, if 2D stack , 2D- 3D
cat   → all tensors must match on every dim EXCEPT the cat dim

 shape [2, 3] + [2, 3] → cat along dim=0 <br>
 <br>
1.check:  dim1 must match → 3==3 ✅ <br>
2.result: [4, 3]  ← dim0 grows, dim1 stays same <br>
3.shape [2, 3] + [2, 3] → cat along dim=1 <br>
4.check:  dim0 must match → 2==2 ✅ <br>
5.result: [2, 6]  ← dim1 grows, dim0 stays same<br>

In [1]:
import torch

t1 = torch.arange(1,4)
t2 = torch.arange(4,7)
print(t1,t2)

# stack in different dimension
print(torch.stack((t1,t2)))
print(torch.stack((t1,t2),dim=1))

# cat - 
print(torch.cat((t1,t2)))  # both are vectors , so dont pass dim.Its always dim=0

#NOT EQUAL SIZE
t1 = torch.arange(1,4)
t2 = torch.arange(4,6)
print(t1,t2)

# cat 
print(torch.cat((t1,t2))) # no issue with different size for vector conactenation

t_list = []
t_list.append(t1)
t_list.append(t2)
t_cat = torch.cat(t_list,dim=0)
print(f"t_cat:{t_cat}")
# stack 
#print(torch.stack((t1,t2))) # RuntimeError: stack expects each tensor to be equal size, but got [3] at entry 0 and [2] at entry 1




tensor([1, 2, 3]) tensor([4, 5, 6])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3]) tensor([4, 5])
tensor([1, 2, 3, 4, 5])
t_cat:tensor([1, 2, 3, 4, 5])


In [2]:
# stack and cat on 2D matrix

mat1 = torch.arange(1,7).reshape(2,3)
mat2 = torch.arange(7,13).reshape(2,3)

print(mat1, mat2)

# stack, dim=0
print(torch.stack((mat1,mat2)))
print(torch.stack((mat1,mat2)).shape)

#stack, dim =1
print(torch.stack((mat1,mat2),dim=1))
print(torch.stack((mat1,mat2),dim=1).shape)

#stack, dim =2
print(torch.stack((mat1,mat2),dim=2))
print(torch.stack((mat1,mat2),dim=2).shape)



tensor([[1, 2, 3],
        [4, 5, 6]]) tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3])
tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])
torch.Size([2, 2, 3])
tensor([[[ 1,  7],
         [ 2,  8],
         [ 3,  9]],

        [[ 4, 10],
         [ 5, 11],
         [ 6, 12]]])
torch.Size([2, 3, 2])


In [ ]:
# stack and cat on 2D matrix

mat1 = torch.arange(1,7).reshape(2,3)
mat2 = torch.arange(7,13).reshape(2,3)
mat3 = torch.arange(13,19).reshape(2,3)

print(mat1, mat2)

# stack, dim=0
print(torch.stack((mat1,mat2,mat3)))
print(torch.stack((mat1,mat2,mat3)).shape)

#stack, dim =1
print(torch.stack((mat1,mat2,mat3),dim=1))
print(torch.stack((mat1,mat2,mat3),dim=1).shape)

#stack, dim =2
print(torch.stack((mat1,mat2,mat3),dim=2))
print(torch.stack((mat1,mat2,mat3),dim=2).shape)

In [ ]:
mat4 = torch.arange(13,19).reshape(2,3)
print(torch.stack((mat1,mat2,mat3,mat4),dim=0))
print(torch.stack((mat1,mat2,mat3,mat4),dim=0).shape)

In [ ]:
# concatination

conc = torch.concat((mat1,mat2))
print(conc)
conc = torch.concat((mat1,mat2),dim=1)
print(conc)
#conc = torch.concat((mat1,mat2),dim=2) #Dimension out of range (expected to be in range of [-2, 1], but got 2)
print(conc)

In [ ]:
# cat cat   → all tensors must match on every dim EXCEPT the cat dim

mat1 = torch.arange(1,7).reshape(2,3)
mat2 = torch.arange(7,10).reshape(1,3)

print(torch.cat((mat1,mat2)))

mat1 = torch.arange(1,7).reshape(3,2)
mat2 = torch.arange(7,10).reshape(3,1)

print(torch.cat((mat1,mat2),dim=1))

# Device - Cuda or cpu


In [ ]:
# Step 1 — check and set device once at top of script
device = 'cuda' if torch.cuda.is_available() else 'cpu'

x = torch.tensor([1.0, 2.0, 3.0])
print(x.device)                     # cpu

# Move to GPU
x = x.to(device)
print(x.device)                     # cuda:0  ← 0 means first GPU

